apiVersion: v1
kind: PersistentVolume
metadata:
  name: url-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"