apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-backend-dep
  namespace: url-short
  labels:
    project: url-shortener
    app: url-backend
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-backend
  template:
    metadata:
      name: url-backend-pod
      labels:
        app: url-backend
        project: url-shortener
    spec:
      containers:
      - name: url-backend-con
        image: ahmedkabil/url-backend:1.64
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: url-config-map
              key: db_host

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: url-secret
              key: db_user

        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: url-secret
              key: db_pass

        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: url-config-map
              key: BACK_HOST

        - name: PORT
          value: "7000"

---
apiVersion: v1
kind: Service
metadata:
  name: url-backend-srv
  namespace: url-short
  labels:
    project: url-shortener
spec:
  selector:
    app: url-backend
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000

        