---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: url-secret
  namespace: url-short
spec:
  encryptedData:
    db_pass: AgAKRi4FWTpvUyM5ot2uZeYXiCbQST6f//LvWVlutvAgSrRZOpyR6QdTHC8eWkicoxfdQEjyAgCPKO+10T4/pscm5oxZRn+gPmMQBnuDJtpVLHeXinB1HJEq9Zg9wCe6HOYiFKgHVI5lCLB9VARrb7YAGlKk2UFeml3i1kl6FAvfmC86t16H49cZy2+mV8oAUkYUdziwgGxvPFlsKFZObNwu+wVraBZDZeV+T9LQ/vOtb4sB+Vyfjdfctn1eenM4+jZ4xNQo2wF5sk1eIfCzlNJ16roS+InO/Ltq+JvnCH/gvRitrk9Hy1cDxukih91A1LDJtgAl5hH2WZX4lbAXHx8vT8wmsXXO0xT2F0JCC6UqHDMUFCmI7/bxs1cnf4Sv9/7dyL2T4PCQhGUGd8ewGKPsVXSWO3Ur6lCDb38Uqz46OvJz0CdHfEF8p90j/xvkSO3JO3pkJoNIM4FJR6gGXZT+7AEmxQHu0hNTKWjtbDTspD8Nk5HQf9GkIo9gR2wYfAeRfI+p5doC9r9tD0LAY+7p73fSyKFY0QpK9zQF0ThDagfl+tB1uWt6GlJRMwCgIUR+H5PbOA5AWQtylws+6ywpK61wKLf58phbkCPwBt6pxiEmGU/4Nl6P32E9bkqsss14fn+EWjjfKaPzbLJf7pDEZg7Z3DddDKRkxIoKWCh4E+feP5/jrYJYm5v177Ns9W5Z6SUgQZko1w==
    db_user: AgCQUrk6tZ4vTYPUVKS3YHRzNnkFKP4zIz4jtk/Ogjgzvc8wqH6OEwv7Hcj89bEtP5d6cm0WhCWvdYhvLWXxdN5E3mRYgF5VGJRwx/wx308lqp58QZlp5uctzQMrUOp+DPeQ2ATn/mqAJnQDK5Uno36kUu1335uymcuQyYcE9HNKDEXzjZi0wbPiqd4v3MuAgJnTme+C4+MAK/gNjxOm75Nkz+sSa14x10t6+77nsYySiB3a2U1cYr9MiXqKhSnfgQYSABWkVy7u1sHzCJ8UyPc4xwJ0QBNcxEVP1pne7uB4LIXoT3UZ+/o9OBHe5l5L58ehUBhN9zsTjHyjdu1/nzlau2X5hZFd5R6i1O+ZigiLsc6bmMH0M9dBP9Vir2x0tKd91nVwfNzrjPUF8Vmm+x4opAoPqYANnsS7gf2q4luogYQTQnlaBkZW8sXNWyD4ovG4rHsQe+dxk74kxO+BNDE2N+kkYgtktPBkoV7fZAq/n2Qin5O4QAY4jPoSYN51neP9vVsN+LL7QJJqSwbKpC+OR54kjaz4N2FHdOvbeQiRK8tODwrIbG8J/JDX7YayeVKEa7tVU8wun0kzj4vn8RHDBmDdhjstDg/C+X9POXoUpWf2JdWjyRx5muyFC7TgMi482gZM+TmmzmdDUEM4sKvf3BQvTaiGItIOF4/GisOgmLRilKpr57vVFRpDfoDetM92gZCad+PY5Q==
  template:
    metadata:
      name: url-secret
      namespace: url-short
    type: Opaque