---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: url-secret
  namespace: url-short
spec:
  encryptedData:
    db_pass: AgA44tgo/HKavDkV/WhNs5kDudRuhw/ocBN3pbpQY3WJk7QnzqXkBtL41kLu68ey97kJyUj4QujOb4ETTpbqWWUt8nZGOxuE5fB4SRRC6RaK1iF3iyzpFYEu00boUyoJU37qrvXb8NTrJPUOMzac2ZTK4u5mCkIUyusfMGexV3xLBK9jKQDQPbN21xG2rjqCxa2tYIJ+LRHe6oNOaqIe5p4bh1XW8nMNGk+8/QnyShclNf4wZTS3bS3TTxkTbyv9OJy7qBfuHbATz6ro1GVDyKziWaSpdTYaxDEuBFsBikt/lsZ49tVF+chDIMQV7MID7mc2M7FNHc8Lka5uJHGazQ3Cfy8hyVcS/jK0RGQ9xGtD/gOJ9pGgA3Mi9z2Ra2XDPqATxxXALVMXBLn+PFgv9kDWuglAMZXT8tGNCfQ9thIta17iICWomzi9jrZ6pDMb5/HFSYXKMD3SD7oHYCxG09yd/NjfRuG9Wd8k7uNy0c7PcSQ+gYXy9OMrCdAI2K020zfOWlXk7g8IHqzzdSmwWXqEPvN5aj+Y2xfP56U21gL439+cdrzWP7IwkxDQeY24RL9pHOG4oSkSdY8lAWfCJ4AxxujytsfmddVowZ9VuT0sQI/lEZCyE+dgKLhgJDBuW0DXmd4CWSpHfi2xrSH/q1Ar3lVzF126sjalRbvQpTWFin3fkCE7DryX6Guo7IVFqHwlbqrrm5PiMA==
    db_user: AgA98Chne+GPxM5GzUgN+mnMzta67PAcoNYVcKsdxFUdFO6vUU2HFO0+QCZiLsNk7bvOd/NXM8KmyTr0RBi1F/YAQKGLbiwawQ+f56NxJnLPhI+il55HVFv298V9ev6WA+MXnWANqSn0TqmFZmcbSQg/A1fSnkrlZnU+ZaZZyqWhFBY7WbxptQ7v9qBmHByZnDA+5mJ6kNCe5CyDls/3Mx2t4cCuqnNSeWekOmi+BFz2k8R0gGHkI/EliwNqiVhfSEvn+9RpGqm2c5p1cj81KTJfeNRX0LbgdHhlSkS8hp2M+CP5EtzVHsPzsSbNL4r/nHFGj1yVQPhoo95ySodP+pMrE4nRZ/ULVVcPLQh0O5IcoKSkXFknmXyjNmO9tj9WWFOvOBFNIPbNJNgvrA+phEi7ejZaI/myNVtsqg56lbx31OixO3yOal6dnYEA3TdfnBvPGIgg34siyAa2Wgy4QsDP6PNhILkVFJIaM9cTZfIt+RnYlRzBKvS4VWiUGm5GrbVqYTs97TA6gN1l0pMA9dk6J6iXFVytn4DR3LU9XIRrCzTMAgT3/KsN95BlGG4Ly61QChYowJYUPGOZKZQa3GISVQDNdo3NrdHKAq+7qVKG6vyMyvhnxBX6JyXZu0duW/cuLnoQ/QeMy44NQ4+X/APAaTdmHAno5R6q9JvE3CUKtkVMxgYtDS0OKHY1m0egfHfHdLx9KXiHMA==
  template:
    metadata:
      name: url-secret
      namespace: url-short
    type: Opaque